package com.fuse.StreamingPlayer;

import android.os.Parcel;
import android.os.Parcelable;

public class Track implements Parcelable {
    public final int Id;
    public final String Name;
    public final String Artist;
    public final String Url;
    public final String ArtworkUrl;
    public final double Duration;

    public Track(int id,
                 String name,
                 String artist,
                 String url,
                 String artworkUrl,
                 double duration) {
        this.Id = id;
        this.Name = name;
        this.Artist = artist;
        this.Url = url;
        this.ArtworkUrl = artworkUrl;
        this.Duration = duration;
    }

    // This lot was generated by Android Studio.. that's kinda cool
    protected Track(Parcel in)
    {
        Id = in.readInt();
        Name = in.readString();
        Artist = in.readString();
        Url = in.readString();
        ArtworkUrl = in.readString();
        Duration = in.readDouble();
    }

    public static final Creator<Track> CREATOR = new Creator<Track>()
    {
        @Override
        public Track createFromParcel(Parcel in)
        {
            return new Track(in);
        }

        @Override
        public Track[] newArray(int size)
        {
            return new Track[size];
        }
    };

    @Override
    public boolean equals(Object obj)
    {
        if (this == null) return false;
        if (this == obj) return true;
        if (this.getClass() != obj.getClass()) return false;
        // Class name is Employ & have lastname
        Track t = (Track) obj;

        return this.Name.equals(t.Name) &&
            this.Artist.equals(t.Artist) &&
            this.Url.equals(t.Url);
    }

    @Override
    public int describeContents()
    {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel parcel, int i)
    {
        parcel.writeInt(Id);
        parcel.writeString(Name);
        parcel.writeString(Artist);
        parcel.writeString(Url);
        parcel.writeString(ArtworkUrl);
        parcel.writeDouble(Duration);
    }
}
