package com.fuse.StreamingPlayer;

import android.os.Parcel;
import android.os.Parcelable;

public class Track implements Parcelable {
    public final int UID;
    public final String Name;
    public final String Artist;
    public final String Url;
    public final String ArtworkUrl;
    public final double Duration;

    public Track(int uid,
                 String name,
                 String artist,
                 String url,
                 String artworkUrl,
                 double duration) {
        this.UID = uid;
        this.Name = name;
        this.Artist = artist;
        this.Url = url;
        this.ArtworkUrl = artworkUrl;
        this.Duration = duration;
    }

    // This lot was generated by Android Studio.. that's kinda cool
    protected Track(Parcel in)
    {
        UID = in.readInt();
        Name = in.readString();
        Artist = in.readString();
        Url = in.readString();
        ArtworkUrl = in.readString();
        Duration = in.readDouble();
    }

    public static final Creator<Track> CREATOR = new Creator<Track>()
    {
        @Override
        public Track createFromParcel(Parcel in)
        {
            return new Track(in);
        }

        @Override
        public Track[] newArray(int size)
        {
            return new Track[size];
        }
    };

    @Override
    public int describeContents()
    {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel parcel, int i)
    {
        parcel.writeInt(UID);
        parcel.writeString(Name);
        parcel.writeString(Artist);
        parcel.writeString(Url);
        parcel.writeString(ArtworkUrl);
        parcel.writeDouble(Duration);
    }
}
